# Generated by Django 4.1.4 on 2023-01-06 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=14)),
                ('telefone_1', models.CharField(max_length=16)),
                ('telefone_2', models.CharField(max_length=16, null=True)),
                ('valor', models.FloatField()),
                ('juros', models.FloatField()),
                ('pagamento_mensal', models.FloatField()),
                ('data', models.DateField(default=datetime.datetime.now)),
                ('vencimento_mensal', models.DateField(default=datetime.datetime.now)),
                ('divida_total_paga', models.BooleanField(default=False)),
            ],
        ),
    ]
