# Generated by Django 4.1.5 on 2023-01-24 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=14)),
                ('telefone', models.CharField(help_text='Insira o telefone com DDD', max_length=16)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=22, verbose_name='Valor R$')),
                ('juros', models.CharField(help_text='Insira a porcentagem de juros', max_length=22, verbose_name='juros %')),
                ('juros_mes', models.DecimalField(decimal_places=2, help_text='Insira o valor dos juros mensais', max_digits=22, verbose_name='Valor de pagamento mensal')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data do empréstimo')),
                ('vencimento_mensal', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('divida_total_paga', models.BooleanField(default=False, verbose_name='Dívida paga')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
