# Generated by Django 4.1.4 on 2023-01-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone_2',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
