# Generated by Django 4.1.5 on 2023-01-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='mensalidade_paga',
            field=models.BooleanField(default=False, verbose_name='Mensalidade Paga'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='divida_total_paga',
            field=models.BooleanField(default=False, verbose_name='Dívida Total Paga'),
        ),
    ]
