# Generated by Django 4.1.4 on 2023-01-07 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_database', '0002_alter_cliente_telefone_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='vencimento_mensal',
            field=models.DateField(default=datetime.datetime),
        ),
    ]
