# Generated by Django 4.1.4 on 2023-01-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_database', '0003_alter_cliente_vencimento_mensal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='vencimento_mensal',
            field=models.DateField(),
        ),
    ]
