# Generated by Django 4.1.5 on 2023-01-26 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_database', '0003_alter_cliente_cpf_alter_cliente_telefone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='mensalidade_paga',
            new_name='checkbox1',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='divida_total_paga',
            new_name='checkbox2',
        ),
    ]
