# Generated by Django 4.1.4 on 2023-01-07 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_database', '0006_rename_telefone_1_cliente_telefone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data',
            field=models.DateField(default=datetime.datetime.now, max_length=10, verbose_name='Data do empréstimo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='juros',
            field=models.FloatField(help_text='Insira a porcentagem de juros', verbose_name='juros %'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='pagamento_mensal',
            field=models.FloatField(help_text='Insira o valor dos juros mensais', verbose_name='Valor de pagamento mensal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='vencimento_mensal',
            field=models.DateField(default=datetime.datetime.now, max_length=10, verbose_name='Data de pagamento'),
        ),
    ]
