# Generated by Django 4.1.4 on 2023-02-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_database', '0006_alter_cliente_parcelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='parcelas_pagas',
            field=models.IntegerField(default=0),
        ),
    ]
