# Generated by Django 4.1.5 on 2023-02-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_database', '0007_cliente_parcelas_pagas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='parcelas_pagas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
