# Generated by Django 4.1.4 on 2023-01-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_database', '0009_alter_cliente_data_alter_cliente_vencimento_mensal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='pagamento_mensal',
            field=models.DecimalField(decimal_places=2, help_text='Insira o valor dos juros mensais', max_digits=10, verbose_name='Valor de pagamento mensal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
