# Generated by Django 4.1.5 on 2023-02-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_database', '0010_alter_cliente_parcelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data_emprestimo',
            field=models.DateField(blank=True, null=True, verbose_name='Data do empréstimo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data do primeiro pagamento'),
        ),
    ]
