# Generated by Django 3.2.5 on 2023-01-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_database', '0010_alter_cliente_pagamento_mensal_alter_cliente_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='pagamento_mensal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Insira o valor dos juros mensais', max_digits=10, verbose_name='Valor de pagamento mensal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
