# Generated by Django 4.1.5 on 2023-02-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_database', '0011_cliente_data_emprestimo_alter_cliente_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='vencimento_mensal',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimento'),
        ),
    ]
