# Generated by Django 3.2.5 on 2023-01-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_database', '0011_auto_20230117_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='valor',
            field=models.CharField(max_length=22),
        ),
    ]
