# Generated by Django 3.2.5 on 2023-01-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_database', '0012_alter_cliente_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='juros',
            field=models.CharField(help_text='Insira a porcentagem de juros', max_length=6, verbose_name='juros %'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='pagamento_mensal',
            field=models.CharField(help_text='Insira o valor dos juros mensais', max_length=22, verbose_name='Valor de pagamento mensal'),
        ),
    ]
