# Generated by Django 4.1.4 on 2023-01-17 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_database', '0013_auto_20230117_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data',
            field=models.DateField(default=datetime.datetime.now, max_length=10, verbose_name='Data do empréstimo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='vencimento_mensal',
            field=models.DateField(default=datetime.datetime.now, max_length=10),
        ),
    ]
