# Generated by Django 3.2.5 on 2023-02-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_database', '0013_alter_cliente_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='observacao',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Pagou em:'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='vencimento_mensal',
            field=models.DateField(blank=True, null=True, verbose_name='Vence:'),
        ),
    ]
