# Generated by Django 3.2.5 on 2023-01-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_database', '0014_alter_cliente_data_alter_cliente_vencimento_mensal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data',
            field=models.DateField(default='18,01,2023', max_length=10, verbose_name='Data do empréstimo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(help_text='Insira o telefone com ddd', max_length=16),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='valor',
            field=models.CharField(max_length=22, verbose_name='Valor R$'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='vencimento_mensal',
            field=models.DateField(default='18,01,2023', max_length=10),
        ),
    ]
