# Generated by Django 3.2.5 on 2023-02-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_database', '0014_auto_20230214_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='parcelas_atrasadas',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Parcelas em Atraso'),
        ),
    ]
