# Generated by Django 3.2.5 on 2023-01-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_database', '0015_auto_20230118_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data',
            field=models.DateField(max_length=10, verbose_name='Data do empréstimo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(help_text='Insira o telefone com DDD', max_length=16),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='vencimento_mensal',
            field=models.DateField(max_length=10),
        ),
    ]
