# Generated by Django 3.2.5 on 2023-02-27 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_database', '0015_cliente_parcelas_atrasadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='data',
        ),
    ]
