# Generated by Django 3.2.5 on 2023-01-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_database', '0016_auto_20230118_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data',
            field=models.DateField(max_length=10, null=True, verbose_name='Data do empréstimo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='vencimento_mensal',
            field=models.DateField(max_length=10, null=True),
        ),
    ]
