# Generated by Django 3.2.5 on 2023-01-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_database', '0019_auto_20230118_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='vencimento_mensal',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Data de Pagamento'),
        ),
    ]
