# Generated by Django 4.1.4 on 2023-01-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_database', '0021_rename_pagamento_mensal_cliente_juros_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='juros',
            field=models.FloatField(help_text='Insira a porcentagem de juros', verbose_name='juros %'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='juros_mes',
            field=models.FloatField(help_text='Insira o valor dos juros mensais', verbose_name='Valor de pagamento mensal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='valor',
            field=models.FloatField(verbose_name='Valor R$'),
        ),
    ]
