# Generated by Django 4.1.4 on 2023-01-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_database', '0022_alter_cliente_juros_alter_cliente_juros_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='juros',
            field=models.DecimalField(decimal_places=2, help_text='Insira a porcentagem de juros', max_digits=10, verbose_name='juros %'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='juros_mes',
            field=models.DecimalField(decimal_places=2, help_text='Insira o valor dos juros mensais', max_digits=10, verbose_name='Valor de pagamento mensal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor R$'),
        ),
    ]
