# Generated by Django 4.1.4 on 2023-01-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_database', '0023_alter_cliente_juros_alter_cliente_juros_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='juros',
            field=models.CharField(help_text='Insira a porcentagem de juros', max_length=22, verbose_name='juros %'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='juros_mes',
            field=models.CharField(help_text='Insira o valor dos juros mensais', max_length=22, verbose_name='Valor de pagamento mensal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='valor',
            field=models.CharField(max_length=22, verbose_name='Valor R$'),
        ),
    ]
