# Generated by Django 3.2.5 on 2023-01-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_database', '0024_alter_cliente_juros_alter_cliente_juros_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='juros_mes',
            field=models.FloatField(help_text='Insira o valor dos juros mensais', max_length=22, verbose_name='Valor de pagamento mensal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='valor',
            field=models.FloatField(max_length=22, verbose_name='Valor R$'),
        ),
    ]
