# Generated by Django 4.1.4 on 2023-01-23 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loan_database', '0026_cliente_usuario_alter_cliente_juros_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='juros_mes',
            field=models.DecimalField(decimal_places=2, help_text='Insira o valor dos juros mensais', max_digits=22, verbose_name='Valor de pagamento mensal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=22, verbose_name='Valor R$'),
        ),
    ]
