# Generated by Django 4.1.5 on 2023-01-23 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_database', '0027_alter_cliente_juros_mes_alter_cliente_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='data',
            new_name='data_emprestimo',
        ),
    ]
