# Generated by Django 4.1.5 on 2023-01-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_database', '0029_rename_data_emprestimo_cliente_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Data do empréstimo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='vencimento_mensal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Data de Pagamento'),
        ),
    ]
