# Generated by Django 4.1.5 on 2023-01-24 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_database', '0031_alter_cliente_data_alter_cliente_vencimento_mensal'),
    ]

    operations = [
    ]
