# Generated by Django 4.1.5 on 2023-01-24 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_database', '0032_auto_20230124_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='data',
            new_name='date',
        ),
    ]
