# Generated by Django 4.1.5 on 2023-01-24 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_database', '0033_rename_data_cliente_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='date',
        ),
    ]
