# Generated by Django 4.1.5 on 2023-01-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_database', '0035_remove_cliente_vencimento_mensal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Data do empréstimo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='vencimento_mensal',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Pagamento'),
        ),
    ]
