# Generated by Django 4.1.5 on 2023-01-24 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_database', '0036_cliente_date_cliente_vencimento_mensal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='date',
            new_name='data',
        ),
    ]
