# Generated by Django 4.1.5 on 2023-01-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_database', '0037_rename_date_cliente_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data',
            field=models.IntegerField(blank=True, null=True, verbose_name='Data do empréstimo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='vencimento_mensal',
            field=models.IntegerField(blank=True, null=True, verbose_name='Data de Pagamento'),
        ),
    ]
